### ISSUE TITLE
Closed loop visualization

### ISSUE THREAD

**Issue by mishrap9** [chantsss/POP-CODE#1]
Hi,

How can I generate gifs as shown in closed loop visualization for any trained model such as QCNet or Forecast-MAE?
For reference: https://github.com/chantsss/POP-CODE?tab=readme-ov-file#closed-loop-visualization-is-like

**Comment by chantsss** [comment]
Hi, 

You can run the script `planning_commonroad.py` and sepcify `create_video 1` to generate closed loop simualtion images. And the GIFs can be generated from images by running `create_video.py`. More details can be found in [README.md](https://github.com/chantsss/POP-CODE/tree/main/py_planning#readme).
